version: '3.4'

services:
  database:
    image: mysql:5.7
    restart: always
    ports:
      - 5432:5432
    environment:
      MYSQL_USER: admin # The MySQL user (useful to connect to the database)
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin  # The MySQL password (useful to connect to the database)
      MYSQL_DATABASE: WeatherInLoop # The MySQL default database (automatically created at first launch)
  command-line:
    build:
     context: .
     dockerfile: Dockerfile
    command: tail -f /dev/null
    links: 
      - database
    volumes:
      - ..:/workspace
    